package com.bunbeauty.shared.navigation

object NavStateHandleParameters {
    const val SELECTED_CATEGORY_UUID_LIST = "selectedCategoryUuidList"
    const val SELECTED_ADDITION_GROUP_UUID = "SELECTED_ADDITION_GROUP_UUID"
    const val SELECTED_ADDITION_UUID_LIST = "SELECTED_ADDITION_UUID_LIST"
    const val CROPPED_IMAGE_URI = "CROPPED_IMAGE_URI"
    const val REFRESH_EDIT_MENU_PRODUCT_ADDITION_GROUPS = "REFRESH_EDIT_MENU_PRODUCT_ADDITION_GROUPS"
    const val UPDATED_DELIVERY_ZONE_UUID = "UPDATED_DELIVERY_ZONE_UUID"
}
